#!/usr/bin/env bash
if tput setaf 1 &> /dev/null; then
	BBLU="$(tput setaf 12)"
	WHT="$(tput setaf 7)"
	BLU="$(tput setaf 4)"
	NORMAL="$(tput sgr0)"
else 
	BLU="|e[1;34m";
	BBLU="|e[1;34m";
	WHT="|e[1;37m";
	NORMAL="|e[0m"
fi

echo "${BBLU}";
echo "    ${BLU}|||||||||||||||||||||${BBLU}lllllllllllllllllllll  ";
echo "    ${BLU}|||||||||||||||||||||${BBLU}lllllllllllllllllllll  ";
echo "    ${BLU}|||||||||||||||||||||${BBLU}lllllllllllllllllllll  ";
echo "    ${BLU}||||||||||||||||||||${WHT}MM${BBLU}llllllllllllllllllll  ";
echo "    ${BLU}|||||||||||||||||||${WHT}MMMM${BBLU}lllllllllllllllllll  ";
echo "    ${BLU}||||||||||||||||||${WHT}MMMMMM${BBLU}llllllllllllllllll  ";
echo "    ${BLU}||||||||${WHT}M${BLU}||||||||${WHT}MMMMMMMM${BBLU}llllllll${WHT}M${BBLU}llllllll  ";
echo "    ${BLU}||||||||${WHT}MM${BLU}||||||${WHT}MMMMMMMMMM${BBLU}lllll${WHT}MMM${BBLU}llllllll  ";
echo "    ${BLU}||||||||${WHT}MMMM${BLU}||||${WHT}MMMMMMMMMM${BBLU}llll${WHT}MMMM${BBLU}llllllll  ";
echo "    ${BLU}||||||||${WHT}MMMMMMMMMMMMMMMMMMMMMMMMMM${BBLU}llllllll  ";
echo "    ${BLU}||||||||${WHT}MMMMMMMMMMMMMMMMMMMMMMMMMM${BBLU}llllllll  ";
echo "    ${BLU}||||||||${WHT}MMMMMMMMMMMMMMMMMMMMMMMMMM${BBLU}llllllll  ";
echo "    ${BLU}||||||||${WHT}MMMMMMMMMMMMMMMMMMMMMMMMMM${BBLU}llllllll  ";
echo "    ${BLU}||||||||${WHT}MMMMMMMMMMMMMMMMMMMMMMMMMM${BBLU}llllllll  ";
echo "     ${BLU}||||||||||||||||||||${BBLU}llllllllllllllllllll  ";
echo "      ${BLU}|||||||||||||||||||${BBLU}lllllllllllllllllll  ";
echo "       ${BLU}||||||||||||||||||${BBLU}llllllllllllllllll  ";
echo "        ${BLU}|||||||||||||||||${BBLU}lllllllllllllllll  ";
echo "         ${BLU}||||||||||||||||${BBLU}llllllllllllllll  ";
echo "           ${BLU}||||||||||||||${BBLU}llllllllllllll  ";
echo "             ${BLU}||||||||||||${BBLU}llllllllllll  ";
echo "                ${BLU}|||||||||${BBLU}lllllllll  ";
echo "                    ${BLU}|||||${BBLU}lllll  ";
echo "${NORMAL}";