#!/usr/bin/env bash
echo ""
echo ""
echo "${BGRN}                     .-'\                  "
echo "${BGRN}                     \:. \                   "
echo "${BGRN}                     |:.  \                   "
echo "${BGRN}                     /::'  \                   "
echo "${BGRN}                  __/:::.   \                   "
echo "${BRED}          _.-'-.'    '.-' '._\-   ;.-'-,         "
echo "${BRED}       . ;    :      :     :      :   :  .        "
echo "${BRED}      / :     :      :                 :  \        "
echo "${BRED}     /        :/\          :   /\ :     :  \        "
echo "${BRED}    ;   :     /\ \   :     :  /\ \      :   ;        "
echo "${BRED}   .    :    /  \ \          /  \ \          .        "
echo "${BRED}   ;        /_)__\ \ :     :/_)__\ \    :    ;        "
echo "${BRED}  ;          ----- ' : ,   : ----- '         ;        "
echo "${BRED}  |    :      :       / \         :     :    |        "
echo "${BRED}  |                  / \ \ :            :    |        "
echo "${BRED}  |    :      :     /___\ \:      :          |        "
echo "${BRED}  |    :      :      ---- '       :          |        "
echo "${BRED}  ;        //;-.,__   :     :   __.-|    :   |        "
echo "${BRED}   ;    :  ||   \ \  /'---'\ \  /  ||        /        "
echo "${BRED}    .    :  \   \_\/       \_\/    //   '    .        "
echo "${BRED}     ;       \'._    /\     /\ _.-'/   :    ;        "
echo "${BRED}      \   :    ._ '-/ /\._./ /\  .'  :     /        "
echo "${BRED}        \  :      -.\/__\__\/_.;'   :    /         "
echo "${BRED}          \  '   :   :        :   :    /         "
echo "${BRED}            - .__         :   :__.'- -        "
echo "${BRED}                  -.. .__.'..-         "
echo "${BRED}          "
echo "${BRED}  ${NORMAL}"
echo ""
